USE [master]
GO
/****** Object:  Database [Club]    Script Date: 2020/01/08 11:01:07 ******/
CREATE DATABASE [Club]
GO
ALTER DATABASE [Club] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [Club] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Club] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Club] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Club] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Club] SET ARITHABORT OFF 
GO
ALTER DATABASE [Club] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Club] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Club] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Club] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Club] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Club] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Club] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Club] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Club] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Club] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Club] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Club] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Club] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Club] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Club] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Club] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Club] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Club] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Club] SET  MULTI_USER 
GO
ALTER DATABASE [Club] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Club] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Club] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Club] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Club] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Club] SET QUERY_STORE = OFF
GO

USE [Club]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

USE [Club]
GO
/****** Object:  Table [dbo].[Club]    Script Date: 2020/01/08 11:01:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Club](
	[ClubID] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
    [Intro] [nvarchar](200) NULL,
	[RunningTime] [datetime] NULL,
	[IgnoreColumn] [nvarchar](50) NULL
) ON [PRIMARY]
GO

USE [Club]
GO

/****** Object:  UserDefinedTableType [dbo].[ClubType]    Script Date: 2020/01/08 11:18:23 ******/
CREATE TYPE [dbo].[ClubType] AS TABLE(
	[ClubID] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[IsActive] [bit] NULL
	PRIMARY KEY CLUSTERED 
(
	[ClubID] ASC
)WITH (IGNORE_DUP_KEY = OFF)
)
GO
ALTER TABLE [dbo].[Club] ADD  CONSTRAINT [DF_Club_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

USE [master]
GO
ALTER DATABASE [Club] SET  READ_WRITE 
GO

USE [Club]
GO
INSERT INTO [Club] (ClubID, [Name], IsActive, Intro, RunningTime, IgnoreColumn)
VALUES
(9, N'§d¬ü´f', CONVERT(bit, 'True'), N'§d', NULL, NULL),
(10, N'§f¨Î¿P', CONVERT(bit, 'True'), N'§f', NULL, NULL),
(11, N'´^§e¨k', CONVERT(bit, 'False'), N'´^', NULL, NULL),
(12, N'¶À«G­»', CONVERT(bit, 'False'), N'¶À', NULL, NULL),
(15, N'¼Ú¶§¨¹Þ³', CONVERT(bit, 'False'), NULL, NULL, NULL),
(16, N'Ã¹©É§g', CONVERT(bit, 'False'), NULL, NULL, NULL),
(17, N'§d²Q®S', CONVERT(bit, 'True'), NULL, NULL, NULL),
(18, N'³¯ÀR©É', CONVERT(bit, 'False'), N'³¯', NULL, NULL),
(19, N'·¨Öö¶Q', CONVERT(bit, 'False'), N'·¨', NULL, NULL),
(20, N'±i¨Î¦m', CONVERT(bit, 'False'), N'±i', NULL, NULL),
(21, N'³¯©{§g', CONVERT(bit, 'True'), N'³¯', NULL, NULL),
(23, N'¤ý³Í¶v', CONVERT(bit, 'False'), N'¤ý', NULL, NULL),
(24, N'¿c©ú½÷', CONVERT(bit, 'False'), NULL, NULL, NULL),
(25, N'¾H°¶¦¨', CONVERT(bit, 'True'), NULL, NULL, NULL),
(26, N'½²©¯Ê¹', CONVERT(bit, 'True'), N'½²', NULL, NULL),
(27, N'¬x¥õ¿«', CONVERT(bit, 'False'), N'¬x', NULL, NULL),
(28, N'¾G¨K§¡', CONVERT(bit, 'True'), N'¾G', NULL, NULL),
(29, N'©PªY©u', CONVERT(bit, 'False'), N'©P', NULL, NULL),
(30, N'ªL©É±d', CONVERT(bit, 'False'), N'ªL', NULL, NULL),
(31, N'³¯«T¦¨', CONVERT(bit, 'True'), N'³¯', NULL, NULL),
(32, N'©P©ôÅï', CONVERT(bit, 'False'), N'©P', NULL, NULL),
(33, N'³\®a¨q', CONVERT(bit, 'True'), N'³\', NULL, NULL),
(34, N'¶À¤h·½', CONVERT(bit, 'True'), N'¶À', NULL, NULL),
(35, N'ÁúÀR©y', CONVERT(bit, 'True'), N'Áú', NULL, N'Ignored'),
(36, N'³s°¶µ¾', CONVERT(bit, 'True'), N'³s', NULL, NULL),
(37, N'¼B«a¦Ë', CONVERT(bit, 'True'), N'¼B', NULL, NULL),
(38, N'ÁÂ¬î»ô', CONVERT(bit, 'True'), N'ÁÂ', NULL, NULL),
(39, N'¤ý¯u§Æ', CONVERT(bit, 'True'), N'¤ý', '2020-01-01 00:00:00.000', NULL)
GO

/****** Object:  Database [Advertisement]    Script Date: 2020/05/18 11:06:57 ******/
CREATE DATABASE [Advertisement]
GO

ALTER DATABASE [Advertisement] SET COMPATIBILITY_LEVEL = 130
GO

ALTER DATABASE [Advertisement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Advertisement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Advertisement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Advertisement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Advertisement] SET ARITHABORT OFF 
GO

ALTER DATABASE [Advertisement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Advertisement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Advertisement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Advertisement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Advertisement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Advertisement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Advertisement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Advertisement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Advertisement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Advertisement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Advertisement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Advertisement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Advertisement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Advertisement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Advertisement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Advertisement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Advertisement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Advertisement] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Advertisement] SET  MULTI_USER 
GO

ALTER DATABASE [Advertisement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Advertisement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Advertisement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Advertisement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Advertisement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Advertisement] SET QUERY_STORE = OFF
GO

USE [Advertisement]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Advertisement] SET  READ_WRITE 
GO

USE [Advertisement]
GO

/****** Object:  Table [dbo].[AdvertisementSetting]    Script Date: 2020/05/18 11:08:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AdvertisementSetting](
	[id] [uniqueidentifier] NOT NULL,
	[typeId] [int] NULL,
	[type] [nvarchar](256) NULL,
	[titleId] [int] NULL,
	[title] [nvarchar](512) NULL,
	[imageName] [nvarchar](256) NULL,
	[imageId] [int] NULL,
	[image] [nvarchar](max) NULL,
	[linkId] [int] NULL,
	[linkName] [nvarchar](256) NULL,
	[link] [nvarchar](max) NULL,
	[weightId] [int] NULL,
	[weight] [int] NULL,
	[state] [int] NULL,
	[stateName] [nvarchar](256) NULL,
	[scheduleId] [int] NULL,
	[scheduleName] [nvarchar](256) NULL,
	[StartTime] [datetime] NULL,
	[EndTime] [datetime] NULL,
	[description] [nvarchar](256) NULL,
	[CreateTime] [datetime] NULL,
	[platformId] [int] NULL,
	[platformName] [nvarchar](50) NULL,
	[LastUpdateTime] [datetime] NULL,
	[AdCode] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

INSERT INTO [AdvertisementSetting] (id, typeId, type, titleId, title, imageName, imageId, image, linkId, linkName, link, weightId, weight, state, stateName, scheduleId, scheduleName, StartTime, EndTime, description, CreateTime, platformId, platformName, LastUpdateTime, AdCode) VALUES
('df31efe5-b78f-4b4b-954a-0078328e34d2', 6, N'1000x90­º­¶¤U', 54, N'¥~³¡¼s§i', N'¥~³¡¼s§i', 92, N' ', 41, N'¥~³¡¼s§i', N' ', 10, 100, 4, N'¥~³¡¼s§i', 0, NULL, NULL, NULL, N'', CONVERT(DATETIME, '2016-02-15 12:10:38.247', 121), 1, N'PC', CONVERT(DATETIME, '2016-02-15 12:10:38.247', 121), NULL)
GO