USE [master]
GO
/****** Object:  Database [Club]    Script Date: 2020/01/08 11:01:07 ******/
CREATE DATABASE [Club]
GO
ALTER DATABASE [Club] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [Club] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Club] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Club] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Club] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Club] SET ARITHABORT OFF 
GO
ALTER DATABASE [Club] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Club] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Club] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Club] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Club] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Club] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Club] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Club] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Club] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Club] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Club] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Club] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Club] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Club] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Club] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Club] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Club] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Club] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Club] SET  MULTI_USER 
GO
ALTER DATABASE [Club] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Club] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Club] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Club] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Club] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Club] SET QUERY_STORE = OFF
GO

USE [Club]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

USE [Club]
GO
/****** Object:  Table [dbo].[Club]    Script Date: 2020/01/08 11:01:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Club](
	[ClubID] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL
) ON [PRIMARY]
GO

USE [Club]
GO

/****** Object:  UserDefinedTableType [dbo].[ClubType]    Script Date: 2020/01/08 11:18:23 ******/
CREATE TYPE [dbo].[ClubType] AS TABLE(
	[ClubID] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[IsActive] [bit] NULL,
    [Intro] [nvarchar](200) NULL
	PRIMARY KEY CLUSTERED 
(
	[ClubID] ASC
)WITH (IGNORE_DUP_KEY = OFF)
)
GO
ALTER TABLE [dbo].[Club] ADD  CONSTRAINT [DF_Club_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

USE [master]
GO
ALTER DATABASE [Club] SET  READ_WRITE 
GO

USE [Club]
GO
INSERT INTO [Club] (ClubID, [Name], IsActive, Intro)
VALUES
(9, N'§d¬ü´f', CONVERT(bit, 'True'), N'§d'),
(10, N'§f¨Î¿P', CONVERT(bit, 'True'), N'§f'),
(11, N'´^§e¨k', CONVERT(bit, 'False'), N'´^'),
(12, N'¶À«G­»', CONVERT(bit, 'False'), N'¶À'),
(15, N'¼Ú¶§¨¹Þ³', CONVERT(bit, 'False'), NULL),
(16, N'Ã¹©É§g', CONVERT(bit, 'False'), NULL),
(17, N'§d²Q®S', CONVERT(bit, 'True'), NULL),
(18, N'³¯ÀR©É', CONVERT(bit, 'False'), N'³¯'),
(19, N'·¨Öö¶Q', CONVERT(bit, 'False'), N'·¨'),
(20, N'±i¨Î¦m', CONVERT(bit, 'False'), N'±i'),
(21, N'³¯©{§g', CONVERT(bit, 'True'), N'³¯'),
(23, N'¤ý³Í¶v', CONVERT(bit, 'False'), N'¤ý'),
(24, N'¿c©ú½÷', CONVERT(bit, 'False'), NULL),
(25, N'¾H°¶¦¨', CONVERT(bit, 'True'), NULL),
(26, N'½²©¯Ê¹', CONVERT(bit, 'True'), N'½²'),
(27, N'¬x¥õ¿«', CONVERT(bit, 'False'), N'¬x'),
(28, N'¾G¨K§¡', CONVERT(bit, 'True'), N'¾G'),
(29, N'©PªY©u', CONVERT(bit, 'False'), N'©P'),
(30, N'ªL©É±d', CONVERT(bit, 'False'), N'ªL'),
(31, N'³¯«T¦¨', CONVERT(bit, 'True'), N'³¯'),
(32, N'©P©ôÅï', CONVERT(bit, 'False'), N'©P'),
(33, N'³\®a¨q', CONVERT(bit, 'True'), N'³\'),
(34, N'¶À¤h·½', CONVERT(bit, 'True'), N'¶À'),
(35, N'ÁúÀR©y', CONVERT(bit, 'True'), N'Áú'),
(36, N'³s°¶µ¾', CONVERT(bit, 'True'), N'³s'),
(37, N'¼B«a¦Ë', CONVERT(bit, 'True'), N'¼B'),
(38, N'ÁÂ¬î»ô', CONVERT(bit, 'True'), N'ÁÂ'),
(39, N'¤ý¯u§Æ', CONVERT(bit, 'True'), N'¤ý')
GO
